name: PacketEventsTest
author: Bram
description: A simple plugin to test PacketEvents
website: https://github.com/retrooper/packetevents
main: com.github.retrooper.packeteventstest.bukkit.PEBukkit
version: ${version}
api-version: '1.13'
folia-supported: true
load: POSTWORLD
depend:
  - packetevents